site_name: telescope.pics
site_url: https://telescope.pics
repo_name: KentAstro/telescope.pics
repo_url: https://github.com/KentAstro/telescope.pics
edit_uri: "edit/main/docs/"

nav:
  - Home: index.md

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: octicons/telescope-fill-24
  palette:
    scheme: slate
    primary: light blue
    accent: lime
  favicon: img/favicon.svg
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - toc.integrate

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - privacy
  - search

extra_css:
  - css/custom.css

extra:
  social:
    - name: YouTube Channel
      link: https://www.youtube.com/channel/UCcCOe9JvkxQDhEwkmTEv08A
      icon: simple/youtube
    - name: KentAstro on GitHub
      link: https://github.com/KentAstro
      icon: fontawesome/brands/github
