site_name: telescope.pics
site_url: https://telescope.pics
repo_name: KentAstro/telescope.pics
repo_url: https://github.com/KentAstro/telescope.pics
edit_uri: "edit/main/docs/"

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: light blue
    accent: lime
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips

plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
  - search
