site_name: telescope.pics
site_url: https://telescope.pics
repo_name: KentAstro/telescope.pics
repo_url: https://github.com/KentAstro/telescope.pics
edit_uri: "edit/main/docs/"

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: yellow
      toggle:
        name: Switch to light mode
        icon: material/lightbulb-outline
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        name: Switch to dark mode
        icon: material/lightbulb
  features:
    - content.action.edit
    - content.action.view

plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
  - search
